.gitignore, .php_cs, .travis.yml, README.md, composer.json, composer.lock
=> Feature: Run php-cs-fixer on Travis

.travis.yml, composer.json, composer.lock, phpunit.xml
=> Enhancement: Run phpunit on Travis

composer.json
=> Fix: Composer

composer.json, src/GitHub.php, tests/GitHubTest.php
=> Enhancement: Provide autoloading configuration

tests/BuilderTest.php
=> Fix: Namespace

tests/Service/PullRequestTest.php
=> Fix: Variable names

tests/Provider/PullRequestTest.php
=> Fix: Test names

README.md
=> Enhancement: Update README with example

.travis.yml, README.md, composer.json, composer.lock
=> Enhancement: CodeClimate

README.md
=> Fix: Install instructions

src/Console/ChangeLogCommand.php, tests/Console/ChangeLogCommandTest.php
=> Enhancement: Create ChangeLog command

README.md, composer.json, composer.lock, github-changelog, src/Console/PullRequestCommand.php, tests/Console/PullRequestCommandTest.php
=> Enhancement: Add console application

github-changelog
=> Fix: Autoloading for console script

README.md
=> Fix: Version foo with rebasing and whatnot

README.md
=> Enhancement: Update readme

github-changelog
*Remember* to increase version number before tagging releases.
=> Application name and version are set

CONTRIBUTING.md, Makefile, composer.json, composer.lock
=> Enhancement: Update fabpot/php-cs-fixer

CONTRIBUTING.md, Makefile
=> Enhancement: Add test target

github-changelog
=> Enhancement: Prepare release

.gitattributes
Sorry my bad, missed the ` export-ignore` part.
=> Fix: Make file is now really excluded

composer.json, composer.lock
=> Fix: Update dependencies

.travis.yml
=> Fix: Only report coverage on success

.travis.yml
=> Fix: Travis

src/Console/PullRequestCommand.php, src/Repository/CommitRepository.php, src/Repository/PullRequestRepository.php
=> Fix: Remove useless docblocks

src/Console/PullRequestCommand.php, src/Repository/CommitRepository.php, src/Repository/PullRequestRepository.php, tests/Console/PullRequestCommandTest.php, tests/Repository/CommitRepositoryTest.php, tests/Repository/PullRequestRepositoryTest.php
=> Fix: Use GitHub domain language

github-changelog
=> Fix: Autoloading

README.md
=> Fix: Remove version requirement

composer.json, composer.lock, src/Console/PullRequestCommand.php, tests/Console/PullRequestCommandTest.php
=> Enhancement: Improve console command output

src/Console/PullRequestCommand.php, tests/Console/PullRequestCommandTest.php
=> Fix: Command output

.travis.yml, composer.json, composer.lock
=> Fix: Reqire codeclimate/php-test-reporter:0.2.0

.travis.yml
=> Fix: Also run builds on PHP5.6, PHP7, and HHVM

.travis.yml
=> Fix: Only collect and report coverage when merging to master

.editorconfig
=> Fix: Add editorconfig support

.php_cs, composer.json, composer.lock, src/Console/PullRequestCommand.php, src/Entity/Commit.php, src/Entity/PullRequest.php, src/Repository/CommitRepository.php, src/Repository/PullRequestRepository.php, tests/Console/PullRequestCommandTest.php, tests/Entity/CommitTest.php, tests/Entity/PullRequestTest.php, tests/Repository/CommitRepositoryTest.php, tests/Repository/PullRequestRepositoryTest.php, tests/Util/FakerTrait.php
This PR
:information_desk_person: For reference, see https://github.com/refinery29/php-cs-fixer-config.
=> Fix: Require refinery29/php-cs-fixer

Makefile
=> Fix: Also validate composer.json and composer.lock

.travis.yml, Makefile, composer.json, composer.lock
This PR
:information_desk_person: For reference, see https://github.com/refinery29/php-cs-fixer-config/compare/0.3.7...0.4.1.
=> Fix: Update refinery29/php-cs-fixer-config

test/Console/PullRequestCommandTest.php
=> Fix: Do not set up system under test in setUp()

test/Console/PullRequestCommandTest.php
=> Fix: Simplify assertions

test/Console/PullRequestCommandTest.php
This PR
:information_desk_person: For reference, see http://symfony.com/doc/current/components/console/introduction.html#testing-commands.
=> Fix: Use CommandTester

src/Resource/Author.php, src/Resource/AuthorInterface.php, test/Resource/AuthorTest.php
=> Enhancement: Implement Author as a value object

composer.json, composer.lock
=> Fix: Update symfony/console and symfony/stopwatch

src/Console/PullRequestCommand.php
=> Fix: Make stopwatch an instance property

src/Console/PullRequestCommand.php, test/Console/PullRequestCommandTest.php
=> Fix: Use SymfonyStyle for output

src/Resource/Range.php, src/Resource/RangeInterface.php, test/Resource/RangeTest.php
=> Enhancement: Implement Range as a value object

src/Resource/Commit.php, src/Resource/CommitInterface.php, test/Resource/CommitTest.php
=> Enhancement: Allow to compare commits

README.md, src/Console/PullRequestCommand.php, src/Repository/CommitRepository.php, src/Repository/PullRequestRepository.php, test/Console/PullRequestCommandTest.php, test/Repository/CommitRepositoryTest.php, test/Repository/PullRequestRepositoryTest.php
=> Enhancement: Use Range

src/Console/GenerateCommand.php
=> Fix: Reverse order

.travis.yml
This PR
💁‍♂️ For reference, see https://codeclimate.com/changelog/57bca9adb116ba032c0010b1.
=> Enhancement: Report coverage on pull request build, too

composer.json, composer.lock
This PR
💁‍♂️ For reference, see https://github.com/symfony/console/compare/v3.0.2...v3.1.5.
=> Enhancement: Update symfony/console

composer.json, composer.lock
This PR
💁‍♂️ For reference, see https://github.com/symfony/stopwatch/compare/v3.0.2...v3.1.5.
=> Enhancement: Update symfony/stopwatch

composer.json, composer.lock, phpunit.xml
This PR
💁‍♂️ For reference, see https://github.com/sebastianbergmann/phpunit/compare/4.8.2...5.6.1.
=> Enhancement: Update phpunit/phpunit

composer.json, composer.lock, src/Console/GenerateCommand.php, src/Repository/PullRequestRepository.php, test/Console/GenerateCommandTest.php, test/Repository/CommitRepositoryTest.php, test/Repository/PullRequestRepositoryTest.php
This PR
💁‍♂️ For reference, see https://github.com/refinery29/php-cs-fixer-config/compare/0.4.1...0.4.20.
=> Enhancement: Update refinery29/php-cs-fixer-config

test/Resource/AuthorTest.php, test/Resource/CommitTest.php, test/Resource/PullRequestTest.php
=> Fix: Use generic data providers

.codeclimate.yml, README.md
=> Enhancement: Switch to Code Climate engines

src/Resource/Author.php, src/Resource/Commit.php, src/Resource/PullRequest.php
=> Fix: Use chained assertions

.gitignore, composer.json, composer.lock, github-changelog, github-changelog.php, src/Console/GenerateCommand.php, test/Console/GenerateCommandTest.php
This PR
💁‍♂️ For reference, see https://github.com/KnpLabs/php-github-api/compare/1.4.14...2.0.0-rc4.
=> Enhancement: Update knplabs/github-api

composer.json, composer.lock
This PR
💁‍♂️ For reference, see https://github.com/KnpLabs/php-github-api/compare/2.0.0-rc4...2.0.1.
=> Fix: Update knplabs/github-api

.php_cs, composer.json, composer.lock, github-changelog.php, src/Console/GenerateCommand.php, src/Repository/CommitRepository.php, src/Repository/PullRequestRepository.php, src/Resource/Author.php, src/Resource/AuthorInterface.php, src/Resource/Commit.php, src/Resource/CommitInterface.php, src/Resource/PullRequest.php, src/Resource/PullRequestInterface.php, src/Resource/Range.php, src/Resource/RangeInterface.php, test/Console/GenerateCommandTest.php, test/Repository/CommitRepositoryTest.php, test/Repository/PullRequestRepositoryTest.php, test/Resource/AuthorTest.php, test/Resource/CommitTest.php, test/Resource/PullRequestTest.php, test/Resource/RangeTest.php
=> Enhancement: Use localheinz/php-cs-fixer-config

composer.json, composer.lock, github-changelog.php, src/Console/GenerateCommand.php, src/Repository/CommitRepository.php, src/Repository/PullRequestRepository.php, src/Resource/Author.php, src/Resource/AuthorInterface.php, src/Resource/Commit.php, src/Resource/CommitInterface.php, src/Resource/PullRequest.php, src/Resource/PullRequestInterface.php, src/Resource/Range.php, src/Resource/RangeInterface.php, test/Console/GenerateCommandTest.php, test/Repository/CommitRepositoryTest.php, test/Repository/PullRequestRepositoryTest.php, test/Resource/AuthorTest.php, test/Resource/CommitTest.php, test/Resource/PullRequestTest.php, test/Resource/RangeTest.php
This PR
💁‍♂️ For reference, see https://github.com/localheinz/php-cs-fixer-config/compare/1.1.0...1.4.0.
=> Enhancement: Update localheinz/php-cs-fixer-config

.travis.yml
=> Fix: Re-encrypt GitHub API token

.travis.yml
=> Fix: Remove useless condition

composer.json, composer.lock
This PR
💁‍♂️ For reference, see https://github.com/codeclimate/php-test-reporter/compare/v0.3.2...v0.4.4.
=> Enhancement: Update codeclimate/php-test-reporter

Makefile
=> Fix: Streamline Makefile

.gitattributes
=> Fix: Streamline .gitattributes

README.md, composer.json
=> Fix: Update README.md

.php_cs, .travis.yml, composer.json, composer.lock, src/Console/GenerateCommand.php, src/Repository/CommitRepository.php, src/Repository/PullRequestRepository.php, src/Resource/Author.php, src/Resource/AuthorInterface.php, src/Resource/Commit.php, src/Resource/CommitInterface.php, src/Resource/PullRequest.php, src/Resource/PullRequestInterface.php, src/Resource/Range.php, src/Resource/RangeInterface.php, test/Unit/Console/GenerateCommandTest.php, test/Unit/Repository/CommitRepositoryTest.php, test/Unit/Repository/PullRequestRepositoryTest.php, test/Unit/Resource/AuthorTest.php, test/Unit/Resource/CommitTest.php, test/Unit/Resource/PullRequestTest.php, test/Unit/Resource/RangeTest.php
=> Fix: Drop support for PHP 5.6

test/Unit/Console/GenerateCommandTest.php, test/Unit/Resource/CommitTest.php, test/Unit/Resource/PullRequestTest.php
=> Enhancement: Yield data from data providers

src/Console/GenerateCommand.php, src/Repository/CommitRepository.php, src/Repository/CommitRepositoryInterface.php, src/Repository/PullRequestRepository.php, src/Repository/PullRequestRepositoryInterface.php, src/Resource/Author.php, src/Resource/AuthorInterface.php, src/Resource/Commit.php, src/Resource/CommitInterface.php, src/Resource/PullRequest.php, src/Resource/PullRequestInterface.php, src/Resource/Range.php, src/Resource/RangeInterface.php, test/Unit/Console/GenerateCommandTest.php, test/Unit/Repository/CommitRepositoryTest.php, test/Unit/Repository/PullRequestRepositoryTest.php, test/Unit/Resource/AuthorTest.php, test/Unit/Resource/CommitTest.php, test/Unit/Resource/PullRequestTest.php, test/Unit/Resource/RangeTest.php
=> Enhancement: Use type and return type declarations

test/Unit/Exception/PullRequestNotFoundTest.php, test/Unit/Exception/ReferenceNotFoundTest.php, test/Unit/ProjectCodeTest.php, test/Unit/Repository/CommitRepositoryTest.php, test/Unit/Repository/PullRequestRepositoryTest.php, test/Unit/Resource/AuthorTest.php, test/Unit/Resource/CommitTest.php, test/Unit/Resource/PullRequestTest.php, test/Unit/Resource/RangeTest.php
=> Enhancement: Add ProjectCodeTest

src/Resource/Repository.php, src/Resource/RepositoryInterface.php, test/Unit/Resource/RepositoryTest.php
=> Enhancement: Implement repository resource

src/Resource/Repository.php, test/Unit/Resource/RepositoryTest.php
=> Enhancement: Allow to create repository resource from string

test/Unit/Resource/RepositoryTest.php
=> Fix: Combine test

src/Console/GenerateCommand.php, src/Exception/InvalidArgumentException.php, src/Resource/Author.php, src/Resource/Commit.php, src/Resource/PullRequest.php, src/Resource/Repository.php, test/Unit/Exception/InvalidArgumentExceptionTest.php, test/Unit/Repository/CommitRepositoryTest.php, test/Unit/Resource/AuthorTest.php, test/Unit/Resource/CommitTest.php, test/Unit/Resource/PullRequestTest.php, test/Unit/Resource/RepositoryTest.php
=> Enhancement: Throw exceptions which implement ExceptionInterface

test/Unit/Console/GenerateCommandTest.php, test/Unit/Resource/AuthorTest.php, test/Unit/Resource/CommitTest.php, test/Unit/Resource/PullRequestTest.php, test/Unit/Resource/RepositoryTest.php, test/Util/DataProvider.php
=> Enhancement: Extract DataProvider

README.md, github-changelog.php, src/Console/GenerateCommand.php, src/Exception/RuntimeException.php, src/Resource/Repository.php, src/Util/Git.php, src/Util/GitInterface.php, src/Util/RepositoryResolver.php, src/Util/RepositoryResolverInterface.php, test/Unit/Console/GenerateCommandTest.php, test/Unit/Exception/RuntimeExceptionTest.php, test/Unit/Resource/RepositoryTest.php, test/Unit/Util/GitTest.php, test/Unit/Util/RepositoryResolverTest.php, test/Util/DataProvider.php
Read the repository owner and name from the local Git configuration.
=> Enhancement: Gather repository metadata from config

src/Resource/User.php, src/Resource/UserInterface.php, test/Unit/Resource/UserTest.php
=> Fix: Rename Author to User

composer.json, composer.lock, src/Resource/User.php, test/Unit/Resource/UserTest.php
=> Fix: Build URL from user name

README.md, src/Console/GenerateCommand.php, src/Repository/PullRequestRepository.php, src/Resource/PullRequest.php, src/Resource/PullRequestInterface.php, test/Unit/Console/GenerateCommandTest.php, test/Unit/Repository/PullRequestRepositoryTest.php, test/Unit/Resource/PullRequestTest.php, test/Util/DataProvider.php
=> Enhancement: Render author in pull request list

src/Console/GenerateCommand.php, test/Unit/Console/GenerateCommandTest.php, test/Util/DataProvider.php
=> Fix: Adjust template variable names

composer.json, composer.lock, src/Resource/CommitInterface.php, src/Resource/RangeInterface.php
This PR
💁‍♂️ For reference, see https://github.com/localheinz/php-cs-fixer-config/compare/1.7.0...1.7.1.
=> Fix: Update localheinz/php-cs-fixer-config

.gitignore
=> Fix: Sort out .gitignore

.travis.yml, README.md
This PR
💁‍♂️ For reference, see https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps.
=> Enhancement: Switch to travis-ci.com

.github/CODE_OF_CONDUCT.md, README.md
=> Enhancement: Add code of conduct

composer.json, composer.lock
=> Enhancement: Allow installation of symfony/symfony:^4.0.0 components

.editorconfig, .gitattributes, .github/CONTRIBUTING.md, .gitignore, .travis.yml, Makefile, composer.json, composer.lock, phpstan.neon
=> Enhancement: Require phpstan/phpstan

.travis.yml
=> Enhancement: Collect coverage on PHP 7.3

phpstan.neon, test/Unit/Console/GenerateCommandTest.php, test/Unit/Repository/CommitRepositoryTest.php, test/Unit/Repository/PullRequestRepositoryTest.php, test/Unit/Resource/PullRequestTest.php, test/Unit/Resource/RangeTest.php, test/Unit/Util/RepositoryResolverTest.php
=> Enhancement: Raise phpstan level from 1 to 2

phpstan.neon, test/Unit/Console/GenerateCommandTest.php, test/Unit/Util/GitTest.php, test/Util/DataProvider.php
=> Enhancement: Raise phpstan level from 2 to 3

phpstan.neon
=> Enhancement: Raise phpstan level from 3 to 4

composer.json, composer.lock, phpstan.neon, src/Repository/PullRequestRepository.php, test/Unit/Repository/PullRequestRepositoryTest.php
=> Enhancement: Raise phpstan level from 4 to 5

phpstan.neon, src/Console/GenerateCommand.php, src/Util/Git.php, test/Unit/Util/RepositoryResolverTest.php, test/Util/DataProvider.php
=> Enhancement: Raise phpstan level from 5 to 6

phpstan.neon
=> Enhancement: Raise phpstan level from 6 to 7 (max)

.travis.yml, Makefile, composer.json, composer.lock, phpstan.neon, src/Console/GenerateCommand.php, src/Repository/CommitRepository.php, src/Resource/Repository.php, src/Util/RepositoryResolver.php, test/Unit/Exception/PullRequestNotFoundTest.php, test/Unit/Exception/ReferenceNotFoundTest.php, test/Unit/Repository/CommitRepositoryTest.php, test/Unit/Repository/PullRequestRepositoryTest.php, test/Unit/Resource/RangeTest.php, test/Unit/Resource/RepositoryTest.php, test/Unit/Util/GitTest.php, test/Unit/Util/RepositoryResolverTest.php
=> Enhancement: Require phpstan/phpstan-strict-rules

.travis.yml, Makefile, test/AutoReview/ProjectCodeTest.php, test/AutoReview/phpunit.xml
=> Enhancement: Extract auto-review test suite

test/AutoReview/SrcCodeTest.php, test/AutoReview/TestCodeTest.php
=> Enhancement: Split tests

composer.json
=> Fix: Description

.github/workflows/continuous-integration.yml, src/Console/GenerateCommand.php, src/Repository/CommitRepository.php, src/Repository/CommitRepositoryInterface.php, src/Repository/PullRequestRepository.php, src/Repository/PullRequestRepositoryInterface.php, test/Unit/Repository/CommitRepositoryTest.php
=> Fix: Run php-cs-fixer with --dry-run option

composer.json, composer.lock, phpstan-baseline.neon, phpstan.neon, src/Util/Git.php, src/Util/RepositoryResolver.php, test/Unit/Console/GenerateCommandTest.php, test/Unit/Repository/CommitRepositoryTest.php, test/Unit/Util/RepositoryResolverTest.php
=> Enhancement: Update phpstan/phpstan and friends

README.md, github-changelog.php
=> Fix: namespace case

.github/settings.yml, .github/workflows/integrate.yaml, .github/workflows/renew.yaml, .php_cs, CHANGELOG.md, composer.json, composer.lock
=> Fix: Drop support for PHP 7.2

psalm-baseline.xml
=> Fix: Regenerate baseline

src/Console/GenerateCommand.php, src/Repository/CommitRepository.php, src/Repository/PullRequestRepository.php, src/Resource/Commit.php, src/Resource/PullRequest.php, src/Resource/Range.php, src/Resource/Repository.php, src/Resource/User.php, src/Util/RepositoryResolver.php
=> Enhancement: Use property type declarations where possible

psalm-baseline.xml, src/Console/GenerateCommand.php
=> Fix: Do not import every single class

.gitattributes, .github/actions/composer/composer/install/run.sh, .github/workflows/integrate.yaml, .github/workflows/renew.yaml, .phive/phars.xml, Makefile, README.md, phpstan.neon, psalm-baseline.xml, psalm.xml, test/Unit/phpunit.xml
=> Enhancement: Synchronize with ergebnis/php-library-template
