README.md
=> Fix: Travis badge

phpunit.xml
=> Fix: Directory should be named tests

.travis.yml
=> Fix: Only test in PHP5.5

composer.lock
=> Fix: composer.lock is not up to date

src/Service/PullRequest.php, tests/Service/PullRequestTest.php
This PR aims to dig out of the rabbit hole again, that is,
=> Fix: Builder should be a PullRequest service

tests/Repository/CommitTest.php, tests/Repository/PullRequestTest.php, tests/Service/CommitTest.php, tests/Service/PullRequestTest.php, tests/Util/DataProviderTrait.php, tests/Util/FakerTrait.php
=> Fix: Reduce duplication in tests

src/Repository/Commit.php, tests/Repository/CommitTest.php
=> Fix: GitHub API returns commits in reverse order, starting with last

composer.json, composer.lock
=> Fix: Show PHP version requirement

README.md
=> Fix: Add install note to README.md

README.md, composer.json, src/Entity/Commit.php, src/Entity/PullRequest.php, src/Provider/PullRequest.php, src/Repository/Commit.php, src/Repository/PullRequest.php, tests/Entity/CommitTest.php, tests/Entity/PullRequestTest.php, tests/Repository/CommitTest.php, tests/Repository/PullRequestTest.php, tests/Util/FakerTrait.php
=> Fix: Rename package and repository

.travis.yml
This PR
See http://blog.sebastianbrosch.de/entwicklung/github-travis-ci-coveralls-code-climate-95/.
=> Fix: Code Climate

src/Repository/Commit.php
=> Fix: all() always returns an array

src/Console/ChangeLogCommand.php, tests/Console/ChangeLogCommandTest.php
=> Fix: Assert exit code is set to 0

src/Console/PullRequestCommand.php, tests/Console/PullRequestCommandTest.php
=> Fix: Catch exceptions in command

src/Repository/Commit.php, tests/Repository/CommitTest.php
=> Fix: Request 250 instead of 30 commits

.gitattributes
These two files show up in the [release downloads](https://github.com/localheinz/github-changelog/releases), so I excluded them.
=> Fix: CHANGELOG.md and Make file excluded from dist

README.md
=> Fix: Track composer.lock only

.codeclimate.yml
=> Fix: Configure Code Climate via file

README.md, src/Console/PullRequestCommand.php, src/Repository/CommitRepository.php, src/Repository/PullRequestRepository.php, tests/Console/PullRequestCommandTest.php, tests/Repository/CommitRepositoryTest.php, tests/Repository/PullRequestRepositoryTest.php
=> Fix: Rename repositories

tests/Console/PullRequestCommandTest.php, tests/Repository/CommitRepositoryTest.php, tests/Repository/PullRequestRepositoryTest.php
=> Fix: Undefined methods, type incompatibility

tests/Console/PullRequestCommandTest.php
=> Fix: Use Faker, because why not

bin/github-changelog, composer.json, composer.lock
=> Fix: Move github-changelog to bin directory

src/Console/PullRequestCommand.php, src/Repository/CommitRepository.php, src/Repository/PullRequestRepository.php, tests/Console/PullRequestCommandTest.php, tests/Repository/CommitRepositoryTest.php, tests/Repository/PullRequestRepositoryTest.php
=> Enhancement: Make end reference an optional argument

Makefile
This PR
:information_desk_person: Run
```
$ make
```
=> Fix: Add it and composer targets

.travis.yml
This PR
:information_desk_person: PHP5.5 is dead, right?
=> Fix: Shift environment variables

README.md, src/Console/PullRequestCommand.php, src/Repository/CommitRepository.php, src/Repository/PullRequestRepository.php, src/Resource/Commit.php, src/Resource/PullRequest.php, test/Console/PullRequestCommandTest.php, test/Repository/CommitRepositoryTest.php, test/Repository/PullRequestRepositoryTest.php, test/Resource/CommitTest.php, test/Resource/PullRequestTest.php
=> Fix: Rename Entity to Resource

README.md, src/Console/PullRequestCommand.php, src/Repository/CommitRepository.php, src/Repository/PullRequestRepository.php, src/Resource/Commit.php, src/Resource/CommitInterface.php, src/Resource/PullRequest.php, src/Resource/PullRequestInterface.php, test/Console/PullRequestCommandTest.php, test/Repository/CommitRepositoryTest.php, test/Repository/PullRequestRepositoryTest.php, test/Resource/CommitTest.php, test/Resource/PullRequestTest.php
=> Fix: Extract interfaces and mark value objects as final

composer.json, composer.lock, src/Resource/Commit.php, src/Resource/PullRequest.php, test/Repository/CommitRepositoryTest.php, test/Resource/CommitTest.php, test/Resource/PullRequestTest.php
=> Fix: Guard against invalid values

test/Console/PullRequestCommandTest.php
=> Fix: Rename methods returning mocks

src/Console/PullRequestCommand.php, test/Console/PullRequestCommandTest.php
=> Fix: Inject dependencies via constructor

test/Resource/PullRequestTest.php
=> Fix: Id needs to be greater than 0

test/Resource/CommitTest.php, test/Resource/PullRequestTest.php
=> Fix: Rename variables in tests

src/Console/PullRequestCommand.php
=> Fix: Use Helper to format time and memory

src/Repository/CommitRepository.php
=> Fix: Use equals() to compare commits

src/Resource/Range.php, src/Resource/RangeInterface.php
=> Fix: Pull mutators into interface

README.md, github-changelog, src/Console/ChangeLogCommand.php, test/Console/ChangeLogCommandTest.php
=>  Fix: Rename command

README.md, github-changelog, src/Console/GenerateCommand.php, test/Console/GenerateCommandTest.php
=> Fix: Rename Command

github-changelog
The application version was way behind the tagged release version.
=> Fix: Align application version

.travis.yml, composer.json, composer.lock
=> Fix: Drop PHP 5.5

composer.json, composer.lock
This PR
💁‍♂️ While at it, it also updates it - for reference, see https://github.com/codeclimate/php-test-reporter/compare/v0.2.0...v0.3.2.
=> Fix: Require codeclimate/php-test-reporter as development dependency

test/Resource/AuthorTest.php, test/Resource/CommitTest.php, test/Resource/PullRequestTest.php
=> Fix: Use expectException() instead of deprecated setExpectedException()

test/Console/GenerateCommandTest.php, test/Repository/CommitRepositoryTest.php, test/Repository/PullRequestRepositoryTest.php, test/Resource/AuthorTest.php, test/Resource/CommitTest.php, test/Resource/PullRequestTest.php, test/Resource/RangeTest.php
=> Fix: Use TestHelper instead of deprecated GeneratorTrait

test/Console/GenerateCommandTest.php, test/Repository/CommitRepositoryTest.php, test/Repository/PullRequestRepositoryTest.php, test/Resource/RangeTest.php
=> Fix: Use createMock()

src/Console/GenerateCommand.php, test/Console/GenerateCommandTest.php, test/Repository/CommitRepositoryTest.php, test/Repository/PullRequestRepositoryTest.php, test/Resource/AuthorTest.php, test/Resource/CommitTest.php, test/Resource/PullRequestTest.php, test/Resource/RangeTest.php
=> Fix: Do not import every class

test/Repository/CommitRepositoryTest.php, test/Repository/PullRequestRepositoryTest.php
=> Fix: Do not fetch faker more often than once

test/Console/GenerateCommandTest.php, test/Repository/CommitRepositoryTest.php, test/Repository/PullRequestRepositoryTest.php, test/Resource/AuthorTest.php, test/Resource/CommitTest.php, test/Resource/PullRequestTest.php, test/Resource/RangeTest.php
This PR
💁‍♂️ There really is no need to extend them.
=> Fix: Mark all tests as final

test/Resource/AuthorTest.php, test/Resource/CommitTest.php, test/Resource/PullRequestTest.php, test/Resource/RangeTest.php
=> Fix: Use shorter variable name

test/Resource/AuthorTest.php, test/Resource/CommitTest.php, test/Resource/PullRequestTest.php, test/Resource/RangeTest.php
=> Fix: Use newly provided assertions

composer.json, composer.lock
This PR
Follows #137.
Follows #140.
=> Fix: Use default minimum stability

test/Console/GenerateCommandTest.php
=> Fix: Identifier should be greater than 0

.travis.yml
=> Fix: Collect coverage on PHP 7.1

.travis.yml, composer.json
This PR
💁‍♂️ For reference, see https://getcomposer.org/doc/06-config.md#preferred-install.
=> Fix: Configure preferred installation method in composer.json

.travis.yml
=> Fix: Replace GITHUB_TOKEN

README.md
=> Fix: Remove --sort-packages flag from installation example

test/Unit/Console/GenerateCommandTest.php, test/Unit/Repository/CommitRepositoryTest.php, test/Unit/Repository/PullRequestRepositoryTest.php, test/Unit/Resource/RangeTest.php
=> Fix: Rename methods creating mocks

src/Resource/Author.php, src/Resource/Commit.php, src/Resource/PullRequest.php
=> Fix: Add missing throws annotations

src/Console/GenerateCommand.php
=> Fix: Remove extra parameter passed in into sprintf()

test/Unit/Resource/CommitTest.php
=> Fix: Add missing test case

README.md, src/Console/GenerateCommand.php, src/Resource/PullRequest.php, src/Resource/PullRequestInterface.php, test/Unit/Console/GenerateCommandTest.php, test/Unit/Repository/PullRequestRepositoryTest.php, test/Unit/Resource/PullRequestTest.php
This PR
💁‍♂️ For reference, see https://developer.github.com/v3/pulls/#get-a-single-pull-request.
=> Fix: Id should be number

src/Repository/CommitRepository.php, test/Unit/Repository/CommitRepositoryTest.php
=> Fix: Consistently return Resource\Range

src/Exception/CommitNotFound.php, src/Exception/ExceptionInterface.php, src/Repository/CommitRepository.php, test/Unit/Exception/CommitNotFoundTest.php, test/Unit/Repository/CommitRepositoryTest.php
=> Enhancement: Throw CommitNotFound exception if commit was not found

src/Exception/ReferenceNotFound.php, src/Repository/CommitRepository.php, test/Unit/Exception/ReferenceNotFoundTest.php, test/Unit/Repository/CommitRepositoryTest.php
=> Fix: Rename CommitNotFound to ReferenceNotFound

src/Console/GenerateCommand.php, src/Exception/ReferenceNotFound.php, src/Repository/CommitRepository.php, src/Repository/PullRequestRepository.php, test/Unit/Console/GenerateCommandTest.php, test/Unit/Exception/ReferenceNotFoundTest.php, test/Unit/Repository/CommitRepositoryTest.php, test/Unit/Repository/PullRequestRepositoryTest.php, test/Unit/Repository/_response/pull-request.json, test/Unit/Resource/PullRequestTest.php
=> Fix: Consistently name variables, parameters and methods

src/Resource/Range.php
=> Fix: Simplify mutation

test/Unit/Console/GenerateCommandTest.php, test/Unit/Repository/CommitRepositoryTest.php
=> Fix: Do not use array_push() where not necessary

src/Console/GenerateCommand.php, src/Repository/CommitRepository.php, src/Repository/CommitRepositoryInterface.php, src/Repository/PullRequestRepository.php, src/Repository/PullRequestRepositoryInterface.php, test/Unit/Console/GenerateCommandTest.php, test/Unit/Repository/CommitRepositoryTest.php, test/Unit/Repository/PullRequestRepositoryTest.php
=> Fix: Extract interfaces

src/Console/GenerateCommand.php, test/Unit/Console/GenerateCommandTest.php, test/Unit/Repository/PullRequestRepositoryTest.php
=> Fix: Use appropriate formatting

src/Repository/PullRequestRepository.php, test/Unit/Console/GenerateCommandTest.php, test/Unit/Repository/CommitRepositoryTest.php, test/Unit/Repository/PullRequestRepositoryTest.php
=> Fix: Use identicalTo() instead of equalTo()

src/Repository/PullRequestRepositoryInterface.php, src/Resource/PullRequest.php, src/Resource/PullRequestInterface.php, test/Unit/Resource/PullRequestTest.php
This PR
Follows #179.
Follows #187.
=> Fix: Pull request number should be an integer

src/Exception/PullRequestNotFound.php, src/Repository/PullRequestRepository.php, src/Repository/PullRequestRepositoryInterface.php, test/Unit/Exception/PullRequestNotFoundTest.php, test/Unit/Repository/PullRequestRepositoryTest.php
=> Enhancement: Throw PullRequestNotFound exception if pull request was not found

test/Unit/Console/GenerateCommandTest.php
=> Fix: Drop argument equal to default

composer.json, composer.lock, test/Unit/Console/GenerateCommandTest.php, test/Unit/Exception/PullRequestNotFoundTest.php, test/Unit/Exception/ReferenceNotFoundTest.php, test/Unit/Repository/CommitRepositoryTest.php, test/Unit/Repository/PullRequestRepositoryTest.php, test/Unit/Resource/AuthorTest.php, test/Unit/Resource/CommitTest.php, test/Unit/Resource/PullRequestTest.php, test/Unit/Resource/RangeTest.php
=> Enhancement: Use localheinz/test-util

src/Console/GenerateCommand.php, test/Unit/ProjectCodeTest.php
=> Fix: Mark GenerateCommand as final

src/Console/GenerateCommand.php, test/Unit/Console/GenerateCommandTest.php
=> Fix: Update description of GenerateCommand

src/Resource/Repository.php, test/Unit/Resource/RepositoryTest.php
=> Enhancement: Reject invalid owner names

test/Unit/Console/GenerateCommandTest.php
=> Fix: Account for single pull request count

test/Unit/Console/GenerateCommandTest.php, test/Unit/Exception/PullRequestNotFoundTest.php, test/Unit/Exception/ReferenceNotFoundTest.php, test/Unit/Repository/CommitRepositoryTest.php, test/Unit/Repository/PullRequestRepositoryTest.php, test/Unit/Resource/AuthorTest.php, test/Unit/Resource/RepositoryTest.php
This PR
Follows #197.
💁‍♂️ The generator creates user names that contain characters not accepted by GitHub. For consistency, it makes sense not to use such a generator, then.
=> Fix: Use slug() instead of userName() generator

test/Unit/Resource/RepositoryTest.php
=> Fix: Ensure that valid owner is accepted by constructor

src/Resource/Repository.php, test/Unit/Resource/RepositoryTest.php
=> Enhancement: Reject invalid repository names

src/Resource/Repository.php, src/Resource/RepositoryInterface.php, test/Unit/Resource/RepositoryTest.php
=> Enhancement: Allow to represent repository as string

test/Unit/Exception/PullRequestNotFoundTest.php, test/Unit/Repository/CommitRepositoryTest.php, test/Unit/Repository/PullRequestRepositoryTest.php, test/Unit/Resource/RepositoryTest.php
=> Fix: Use numberBetween(1) instead of randomNumber() generator

README.md, src/Console/GenerateCommand.php, src/Exception/PullRequestNotFound.php, src/Exception/ReferenceNotFound.php, src/Repository/CommitRepository.php, src/Repository/CommitRepositoryInterface.php, src/Repository/PullRequestRepository.php, src/Repository/PullRequestRepositoryInterface.php, test/Unit/Console/GenerateCommandTest.php, test/Unit/Exception/PullRequestNotFoundTest.php, test/Unit/Exception/ReferenceNotFoundTest.php, test/Unit/Repository/CommitRepositoryTest.php, test/Unit/Repository/PullRequestRepositoryTest.php
=> Enhancement: Use repository resource instead of owner and name separately

README.md, src/Console/GenerateCommand.php, test/Unit/Console/GenerateCommandTest.php
=> Enhancement: Combine owner and repository argument into repository argument

src/Resource/Repository.php, test/Unit/Exception/PullRequestNotFoundTest.php, test/Unit/Exception/ReferenceNotFoundTest.php, test/Unit/Repository/CommitRepositoryTest.php, test/Unit/Repository/PullRequestRepositoryTest.php, test/Unit/Resource/RepositoryTest.php
=> Enhancement: Allow to create resource from owner and name

src/Console/GenerateCommand.php, test/Unit/Console/GenerateCommandTest.php
=> Fix: Require value for options

github-changelog.php
=> Fix: Remove shebang from github-changelog.php

src/Console/GenerateCommand.php
=> Fix: Wording

src/Resource/Repository.php, test/Util/DataProvider.php
=> Fix: Dots in repository names should be acceptable

test/Unit/Util/GitTest.php
=> Fix: Add remote name to list of remote names and use in_array()

composer.json, composer.lock, phpstan.neon, test/Unit/Util/GitTest.php
=> Enhancement: Require phpstan/phpstan-deprecation-rules

composer.json, composer.lock, phpstan.neon
=> Enhancement: Require jangregor/phpstan-prophecy

.gitignore, .travis.yml, infection.json
=> Enhancement: Store infection build files in .build/infection

.travis.yml
=> Fix: Explicitly list infection stage

test/Unit/Console/GenerateCommandTest.php, test/Unit/Exception/PullRequestNotFoundTest.php, test/Unit/Exception/ReferenceNotFoundTest.php, test/Unit/Repository/CommitRepositoryTest.php, test/Unit/Repository/PullRequestRepositoryTest.php, test/Unit/Resource/PullRequestTest.php, test/Unit/Util/RepositoryResolverTest.php
=> Fix: Add missing uses annotations

test/Unit/Resource/RangeTest.php
=> Fix: Class name reference in covers annotation

.travis.yml, Makefile, test/Unit/Console/GenerateCommandTest.php, test/Unit/Repository/CommitRepositoryTest.php, test/Unit/Repository/PullRequestRepositoryTest.php, test/Unit/Resource/RangeTest.php, test/Unit/Util/RepositoryResolverTest.php
=> Enhancement: Use phpspec/prophecy for test doubles

composer.json, composer.lock, phpstan.neon
=> Fix: Remove phpstan/phpstan-phpunit

composer.json, composer.lock, test/AutoReview/SrcCodeTest.php, test/Unit/Console/GenerateCommandTest.php, test/Unit/Exception/InvalidArgumentExceptionTest.php, test/Unit/Exception/PullRequestNotFoundTest.php, test/Unit/Exception/ReferenceNotFoundTest.php, test/Unit/Exception/RuntimeExceptionTest.php, test/Unit/Repository/CommitRepositoryTest.php, test/Unit/Repository/PullRequestRepositoryTest.php, test/Unit/Resource/CommitTest.php, test/Unit/Resource/PullRequestTest.php, test/Unit/Resource/RangeTest.php, test/Unit/Resource/RepositoryTest.php, test/Unit/Resource/UserTest.php, test/Unit/Util/GitTest.php, test/Unit/Util/RepositoryResolverTest.php, test/Util/DataProvider.php
=> Enhancement: Use ergebnis/test-util instead of localheinz/test-util

.github/workflows/integrate.yaml, Makefile, infection.json
=> Fix: Configure mutation scores via configuration file

infection.json, phpstan-baseline.neon, test/Unit/Util/RepositoryResolverTest.php
=> Fix: Skip flaky test

github-changelog.php, src/Console/GenerateCommand.php, test/Unit/Console/GenerateCommandTest.php
=> Fix: Inject hard dependency
